kind: pipeline
type: docker
name: publish


workspace:
  path: /portfolio

when:
    branch:
    - master

steps:
- name: build
  image: node:15
  commands:
  - yarn
  - cd storybook
  - yarn
  - yarn build-storybook
  - touch storybook-static/.nojekyll
- name: publish  
  image: plugins/gh-pages
  settings:
    username:
      from_secret: github_username
    password:
      from_secret: github_password
    pages_directory: storybook-static/

